# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.upsun.com/anchors/fixed/cli/"
  version "5.10.3"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/upsun/cli/releases/download/v5.10.3/platform_5.10.3_darwin_all.tar.gz"
    sha256 "9e072db1a26dff6b35a02c202fea158616d99d17502968735798fbe6c775aa00"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.3/platform_5.10.3_linux_amd64.tar.gz"
      sha256 "2f86d85c7609085011a7f52ca518c7ec09d192dc573ad465dbad05f8e6aacfde"
      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.3/platform_5.10.3_linux_arm64.tar.gz"
      sha256 "a894128a4973c4f3bee2ff7ab2c067bc92d274dfc5060b7489761070269a9020"
      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
