# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.upsun.com/anchors/fixed/cli/"
  version "5.10.4"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/upsun/cli/releases/download/v5.10.4/platform_5.10.4_darwin_all.tar.gz"
    sha256 "d9662ba628e2238ccbc11cf8aabdaf6f82f825dfce115c00d82f03bd50ced39c"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.4/platform_5.10.4_linux_amd64.tar.gz"
      sha256 "0b9c7e6ceb16825d29af51a32bb38366e370aa5df0b71a26e2c3f6d42c7bdca4"
      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.4/platform_5.10.4_linux_arm64.tar.gz"
      sha256 "50b6d7edf3254108023a870396cf0b2ec51ce72cda54b3e580c38029f31b3e2d"
      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
