# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpsunCli < Formula
  desc "Upsun CLI"
  homepage "https://docs.upsun.com/anchors/cli/"
  version "5.10.3"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/upsun/cli/releases/download/v5.10.3/upsun_5.10.3_darwin_all.tar.gz"
    sha256 "7748a195dd7e61be15727176f062dd5be4bfe831d8bb2c69741422b44802f50f"

    def install
      bin.install "upsun"
      generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.3/upsun_5.10.3_linux_amd64.tar.gz"
      sha256 "11c4a824874696d56b1753887dfb8d4b4e3cccd466e3e2480624312617c2cbdb"
      def install
        bin.install "upsun"
        generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.3/upsun_5.10.3_linux_arm64.tar.gz"
      sha256 "256b20c2f9a5b595937520c15ea3982f6fda9702336a95a92e0d8db97fb427ee"
      def install
        bin.install "upsun"
        generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/upsun --version"
  end
end
