# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpsunCli < Formula
  desc "Upsun CLI"
  homepage "https://docs.upsun.com/anchors/cli/"
  version "5.10.0-alpha6"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/upsun/cli/releases/download/v5.10.0-alpha6/upsun_5.10.0-alpha6_darwin_all.tar.gz"
    sha256 "6a1ebd655723dbd8e7bc8939ed2204a22be65ff2a030c2880bfdfdcbf22b9730"

    def install
      bin.install "upsun"
      generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.0-alpha6/upsun_5.10.0-alpha6_linux_amd64.tar.gz"
      sha256 "5b1c16b902a482ec96c22208fb7ac6d90a0d6f65ec27ab949d603d77699d9ef6"
      def install
        bin.install "upsun"
        generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upsun/cli/releases/download/v5.10.0-alpha6/upsun_5.10.0-alpha6_linux_arm64.tar.gz"
      sha256 "d36e9f1b9ab5438dfb989cb997686413037da55cbe7b5defdfd309721de9c47d"
      def install
        bin.install "upsun"
        generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/upsun --version"
  end
end
